### ISSUE TITLE
crash when going to installer

### ISSUE THREAD

**Issue by ehsan58** [liuxu623/MSI-GT72S-CLOVER#1]
hi how r u sir?  it have issue when booting to installer

![img_2017-03-01 10 15 05](https://cloud.githubusercontent.com/assets/3213169/23447354/fa4583fc-fe67-11e6-93df-bc6cd8fd858e.jpg)

**Comment by JessyTang** [comment]
这个应该是OsxAptioFixDrv无法分配内存块，你可以用OsxAptioFix2Drv重新尝试，跟Config，kext等无关

**Comment by JessyTang** [comment]
It means that the clover can't alloc the memory with OsxAptioFixDrv.efi，And I recommend that you can use OsxAptioFix2Drv.efi. Warning: Don't use them together.

**Comment by ehsan58** [comment]
ok i will try to use that 💯

**Comment by liuxu623** [comment]
use [OsxAptioFixDrv256m-64.efi](https://raw.githubusercontent.com/liuxu623/MSI-GT72S-Hackintosh/master/EFI/CLOVER/drivers64UEFI/) instead of OsxAptioFixDrv.efi
