### ISSUE TITLE
GT72S黑苹果 Webdrive花屏现象

### ISSUE THREAD

**Issue by JessyTang** [liuxu623/MSI-GT72S-CLOVER#2]
我之前在PCBETA上看到了你的黑苹果EFI文件，非常感谢你的EFI让我成功安装了黑苹果，我的笔记本是GT72S，970m的显卡，和你的类似。

但是在装WebDrive的时候，使用nvda_drv=1重启后出现了花屏，但我确认系统确实是可以进入的，因为我可以从局域网访问这台电脑，我之前以为是DSDT SSDT我们两个之间存在差异导致的，就自己尝试了不带DSDT SSDT安装后还是出现了这个问题，我在PCBETA上发帖有同样的电脑的人回复了我，他提出了可能的原因：

>同GT72 2qe，980M和你情况一样，你远程可以进系统，其实是已经驱动了的，只是Mac找不到输出端口。我从Linux jump出来的端口信息和980m驱动时的ioreg文件，你可以发现单显HD4600时，输出端口时eDP-1，而单卡980M时，输出端口为DP-0，我想这就是问题的根本原因，如果能将DP-0的端口信号弄到eDP-1，问题估计就能解决了”。

不知道你在当时安装的时候有没有出现这个问题？或者你对这个原因是否有解决的想法？希望收到你的回复！非常感谢！

**Comment by liuxu623** [comment]
非常抱歉，我没有遇到过这个问题，之前也有人问过我相同的问题，但是最终没能解决，最近几个月也没怎么关注黑苹果了

**Comment by liuxu623** [comment]
好像除了980，gt72s的980m和970m版本都有这个问题

**Comment by JessyTang** [comment]
非常感谢，我尝试更换下1070试试看

**Comment by liuxu623** [comment]
@JessyTang 这个应该和显卡型号无关，是主板的问题，970m/980m和980的主板不一样，具体哪里不一样我也说不清楚，如果出厂是980m版本的GT72S，即使更换了980也是同样的问题，不过你如果有1070可以试下，欢迎反馈下测试结果
