### ISSUE TITLE
Have you fix WIFI disappear problem?

### ISSUE THREAD

**Issue by JessyTang** [liuxu623/MSI-GT72S-CLOVER#3]
I bought a Dragon Edition MSI Laptop like you. And I use your efi. I replace the ngff network card to BCM94352Z. However I can't use WIFI. And Maybe Bluetooth is useless. Can you give me some advice?

**Comment by liuxu623** [comment]
I can't use BCM94352Z WIFI too,so I use DW1830 (BCM943602BAED)  now.

**Comment by JessyTang** [comment]
Thanks for your help. I follow your way to hackintosh :）

**Comment by JessyTang** [comment]
And I have some issues, can i communicate with you by QQ or E-mail? Thank you very much!

**Comment by liuxu623** [comment]
QQ 93033903
